### ISSUE TITLE
Issue with `composer install` on the last version.

### ISSUE THREAD

**Issue by shulard** [hoaproject/Irc#23]
I've retrieved the last commits on master to work on the #22. When I ran `composer install`, I've got the problem detailed in hoaproject/Central#32.

I retrieved the `hoa/core` package because the `hoa/stream` used is 0.15.x. To make it works I needed to change the `hoa/stream` version constraint to : `"hoa/socket": "~1.0"`.

With that change, everything is fine :smile:.

**Comment by Hywan** [comment]
Correct. `hoa/socket` must be `~1.0`. Can you make a PR please?

**Comment by Hywan** [comment]
Closed by #24.
